import React, { Component } from 'react';


class Instruction extends Component{
    render(){
        return(
            
            <div className='contener instruction'>
            <ol>
                <li>Use your logic in order to guess a 3-digit secret number generated by program</li>
                <li>The number is formed with digits from 0 to 9</li>
                <li>Each digit appears once at most</li>
                <li>Program will tell you how many digits are correct</li>
                <li> And how many digits are on right positions</li>
                <li>You have only 10 moves</li>
            </ol>
            </div>
        )
    }
}
export default Instruction